### ISSUE TITLE
Additional Controller Support?

### ISSUE THREAD

**Issue by bsau3130** [rasathus/circadianLighting#5]
Hi Rasathus!

(Feature Request)

How hard would it be to implement support for the LPD8806 controller?

**Comment by rasathus** [comment]
It looks to be the same 3 byte rgb structure as the ws2801, just with some extra zero bits clocked in between each set. If I can find some to play with it shouldn't be a problem. 

I'll try and add it to a test branch. Have you got anything to test it against?

**Comment by bsau3130** [comment]
I have a 5 meter strip set up and working. I'll gladly test for you. If you want a meter or two for yourself I will gladly send you some

**Comment by rasathus** [comment]
I've added a guesswork implementation of the LPD8806 to pigredients here ... https://github.com/rasathus/pigredients/tree/lpd8806-support

Could you check it out, install it and see if the example looks sensible.  It will assume you have 25 LEDS in a chain, if not you'll need to alter 'led_chain = lpd8806.LPD8806_Chain()' to 'led_chain = lpd8806.LPD8806_Chain(ics_in_chain=<number_of_leds>)' in the example.

If it works ill make the amendment to the circadian project to support it.

**Comment by bsau3130** [comment]
Thanks heaps for implementing this. As luck would have it my power supply has just failed. I've ordered a new supply, i'll let you know how everything goes.

**Comment by rasathus** [comment]
It's always the way. Let me know if it works. If so ill tidy it up and add the supported flag on the circadian side.

**Comment by bsau3130** [comment]
I figured I may as well use a modified ATX power supply to get me by for now. I have tried your example, here is a link to what it looks like. Does this look correct to you? 

http://www.youtube.com/watch?v=V8oXQOmEO_Y

I'll happily order a few meters on adafruit and get them shipped to you if you'd like. 

Im sorry I cant be more help, I'm still learning.

Here is a link to a working library. https://github.com/ctcusick/RPi-LPD8806

I did find a decent run down on how the strip works from an adafruit 8806 library for the Arduino (LPD8806.h header)  Huge apologies for the wall of text.
 --
Clearing up some misconceptions about how the LPD8806 drivers work:

The LPD8806 is not a FIFO shift register.  The first data out controls the
LED _closest_ to the processor (unlike a typical shift register, where the
first data out winds up at the _furthest_ LED).  Each LED driver 'fills up'
with data and then passes through all subsequent bytes until a latch
condition takes place.  This is actually pretty common among LED drivers.

All color data bytes have the high bit (128) set, with the remaining
seven bits containing a brightness value (0-127).  A byte with the high
bit clear has special meaning (explained later).

The rest gets bizarre...

The LPD8806 does not perform an in-unison latch (which would display the
newly-transmitted data all at once).  Rather, each individual byte (even
the separate G, R, B components of each LED) is latched AS IT ARRIVES...
or more accurately, as the first bit of the subsequent byte arrives and
is passed through.  So the strip actually refreshes at the speed the data
is issued, not instantaneously (this can be observed by greatly reducing
the data rate).  This has implications for POV displays and light painting
applications.  The 'subsequent' rule also means that at least one extra
byte must follow the last pixel, in order for the final blue LED to latch.

To reset the pass-through behavior and begin sending new data to the start
of the strip, a number of zero bytes must be issued (remember, all color
data bytes have the high bit set, thus are in the range 128 to 255, so the
zero is 'special').  This should be done before each full payload of color
values to the strip.  Curiously, zero bytes can only travel one meter (32
LEDs) down the line before needing backup; the next meter requires an
extra zero byte, and so forth.  Longer strips will require progressively
more zeros.  *(see note below)

In the interest of efficiency, it's possible to combine the former EOD
extra latch byte and the latter zero reset...the same data can do double
duty, latching the last blue LED while also resetting the strip for the
next payload.

So: reset byte(s) of suitable length are issued once at startup to 'prime'
the strip to a known ready state.  After each subsequent LED color payload,
these reset byte(s) are then issued at the END of each payload, both to
latch the last LED and to prep the strip for the start of the next payload
(even if that data does not arrive immediately).  This avoids a tiny bit
of latency as the new color payload can begin issuing immediately on some
signal, such as a timer or GPIO trigger.

Technically these zero byte(s) are not a latch, as the color data (save
for the last byte) is already latched.  It's a start-of-data marker, or
an indicator to clear the thing-that's-not-a-shift-register.  But for
conversational consistency with other LED drivers, we'll refer to it as
a 'latch' anyway.
- This has been validated independently with multiple customers'
  hardware.  Please do not report as a bug or issue pull requests for
  this.  Fewer zeros sometimes gives the _illusion_ of working, the first
  payload will correctly load and latch, but subsequent frames will drop
  data at the end.  The data shortfall won't always be visually apparent
  depending on the color data loaded on the prior and subsequent frames.
  Tested.  Confirmed.  Fact.
  */

**Comment by rasathus** [comment]
Its something, but not quite what I was expecting.  From reading your text above,  I suspect the colour order im using is incorrect. 

The example should do the following ...

Set led 24 to purple and sleep for 2 seconds.
turn led 24 off, and sleep for1/2 second.
flash white
flash red
flash green
flash blue
flash white
run a random cycle sequence
turn all the leds off.

If your happy to send me a few of them I can take a proper look.  I should only need about 5 leds or so to make sure I get the RGB order correct and don't have any sequence errors.  If you want to contac tme at pigredients@chrisfane.co.uk  we can talk it over.

**Comment by rasathus** [comment]
Support added in commit  3a408dcff31e6f46abf4b8103aefeb2bb58a3a6a
